"""Keyword module."""

from enum import Enum


class Keyword(Enum):
    """Effect keywords."""

    ATTACK = "ATTACK"
    BLEED = "BLEED"
    BLOCK = "BLOCK"
    BURN = "BURN"
    CLEANSE = "CLEANSE"
    COUNTER = "COUNTER"
    CURSE = "CURSE"
    DODGE = "DODGE"
    DRAIN = "DRAIN"
    FORTIFY = "FORTIFY"
    FRAGILE = "FRAGILE"
    FREEZE = "FREEZE"
    HEAL = "HEAL"
    HEMORRAGY = "HEMORRAGY"
    HEX = "HEX"
    MAGIC = "MAGIC"
    MANA = "MANA"
    MANA_DRAIN = "MANA_DRAIN"
    OMNI_DRAIN = "OMNI_DRAIN"
    PIERCE = "PIERCE"
    POISON = "POISON"
    SCORCH = "SCORCH"
    STRENGTHEN = "STRENGTHEN"
    STUN = "STUN"
    TAUNT = "TAUNT"
    THORNS = "THORNS"
    TOXIC = "TOXIC"
    WEAKEN = "WEAKEN"
