"""Trigger condition for effects, skills, etc."""

from enum import Enum


class Trigger(Enum):
    ATTACK = "ATTACK"
    BEING_ATTACKED = "BEING_ATTACKED"
    BEING_BUFFED = "BEING_BUFFED"
    BEING_DEBUFFED = "BEING_DEBUFFED"
    BEING_DEFENDED = "BEING_DEFENDED"
    BEING_DAMAGED = "BEING_DAMAGED"
    BEING_HEALED = "BEING_HEALED"
    BUFF = "BUFF"
    DAMAGE = "DAMAGE"
    DEBUFF = "DEBUFF"
    DEFEND = "DEFEND"
    EQUIPMENT_EQUIPPED = "EQUIPMENT_EQUIPPED"
    EQUIPMENT_REMOVED = "EQUIPMENT_REMOVED"
    HEALING = "HEALING"
    ITEM_USED = "ITEM_USED"
    RUN = "RUN"
    SKILL_USED = "SKILL_USED"
    SUMMON = "SUMMON"
    TURN_END = "TURN_END"
    TURN_START = "TURN_START"
