"""Trigger condition for effects, skills, etc."""

from enum import Enum


class Trigger(Enum):
    """Triggers for Effects or Skills activations."""
    ATTACK = "ATTACK"
    BEING_ATTACKED = "BEING_ATTACKED"
    BEING_BUFFED = "BEING_BUFFED"
    BEING_DEBUFFED = "BEING_DEBUFFED"
    BEING_DEFENDED = "BEING_DEFENDED"
    BEING_DAMAGED = "BEING_DAMAGED"
    BEING_HEALED = "BEING_HEALED"
    BUFF = "BUFF"
    DAMAGE = "DAMAGE"
    DEATH = "DEATH"
    DEBUFF = "DEBUFF"
    DEFEND = "DEFEND"
    EQUIPMENT_EQUIPPED = "EQUIPMENT_EQUIPPED"
    EQUIPMENT_REMOVED = "EQUIPMENT_REMOVED"
    HEALING = "HEALING"
    ITEM_USED = "ITEM_USED"
    ROLL = "ROLL"
    ROUND_END = "ROUND_END"
    ROUND_START = "ROUND_START"
    RUN = "RUN"
    SKILL_USED = "SKILL_USED"
    SUMMON = "SUMMON"
    TURN_END = "TURN_END"
    TURN_START = "TURN_START"
